/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Sort                                   */
/*      FILE         :  Sort.c                                 */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX610                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                              
                                                                           
extern void asm_sort(unsigned int *addr, unsigned int size);

unsigned int src_array[8];
                                                                          
/***********************************************************************/
/*                                                                     */
/*  FILE        :Main.c or Main.cpp                                    */
/*  DATE        :Tue, Oct 31, 2006                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :                                                      */
/*                                                                     */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

#pragma inline_asm fatorial
unsigned int fatorial(unsigned int data)
{
	MOV.L R1,R3	; copy parameter to R3
	MOV.L #1,R1	; init R1 (result) with 1
	MOV.L #1,R2	; R2 is an auxiliary register
?:			; this is a temporary label
	MUL R2,R1	; perform R1 = R2 * R1
	ADD #1,R2	; add one to R2
	SUB #1,R3	; decrement R3
	BNZ.B ?-	; branch to previous label if R3 not zero
}

void main(void)
{
	src_array[0] = 500;
	src_array[1] = 5;
	src_array[2] = 1000;
	src_array[3] = 10000;
	src_array[4] = 8;
	src_array[5] = 22;
	src_array[6] = 42;
	src_array[7] = 1001;
	asm_sort(src_array,8);
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
